name: Build ML Worker Docker image and push to registry with dev tag

on:
  push:
    branches:
      - main
      - andrey/docker-buildx
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: amd64,arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Login to Docker registry
        uses: docker/login-action@v2
        if: ${{ steps.extract_branch.outputs.branch == 'main' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@master
        env:
          TAG: dev
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true

#      - name: Invoke deployment hook
#        if: ${{ steps.extract_branch.outputs.branch == 'main' }}
#        run: |
#          curl -L --silent --max-time 900 ${{ secrets.TEST_SERVER_WEBHOOK_URL_BASE }}/redeploy-dev

      - name: Remove containers and volumes
        run: docker system prune -a -f


